import fs from "fs";
import path from "path";
import type {
  ComponentInfo,
  DesignTokens,
  ProgressMessage,
  ProjectConfig,
  ScanResult,
  StylingApproach,
} from "../types.js";

type Emit = (msg: ProgressMessage) => void;

interface GenerateOptions {
  config: ProjectConfig;
  scan: ScanResult;
  emit: Emit;
  dryRun: boolean;
}

function primaryApproach(approaches: StylingApproach[]): StylingApproach {
  if (approaches.includes("tailwind")) return "tailwind";
  if (approaches.includes("styled-components")) return "styled-components";
  if (approaches.includes("css-modules")) return "css-modules";
  return "tailwind";
}

function write(filePath: string, content: string, dryRun: boolean) {
  if (dryRun) return;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

// ── tokens.ts ────────────────────────────────────────────
function renderTokensFile(tokens: DesignTokens): string {
  const section = (obj: Record<string, string>) =>
    Object.entries(obj)
      .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
      .join("\n");

  return `// Generated by @icydotdev/lumen — raw inferred token values.
export const tokens = {
  colors: {
${section(tokens.colors)}
  },
  spacing: {
${section(tokens.spacing)}
  },
  typography: {
${section(tokens.typography)}
  },
  borderRadius: {
${section(tokens.borderRadius)}
  },
  shadows: {
${section(tokens.shadows)}
  },
} as const;

export type Tokens = typeof tokens;
`;
}

// ── theme.ts ─────────────────────────────────────────────
function renderThemeFile(approach: StylingApproach): string {
  if (approach === "styled-components") {
    return `// Generated by @icydotdev/lumen — ThemeProvider theme object.
import { tokens } from "./tokens";

export const theme = {
  colors: tokens.colors,
  spacing: tokens.spacing,
  typography: tokens.typography,
  borderRadius: tokens.borderRadius,
  shadows: tokens.shadows,
};

export type Theme = typeof theme;
`;
  }

  if (approach === "css-modules") {
    return `// Generated by @icydotdev/lumen — CSS custom properties.
import { tokens } from "./tokens";

export function themeToCssVars(): string {
  const lines: string[] = [":root {"];
  for (const [k, v] of Object.entries(tokens.colors))
    lines.push(\`  --color-\${k}: \${v};\`);
  for (const [k, v] of Object.entries(tokens.spacing))
    lines.push(\`  --\${k}: \${v};\`);
  lines.push("}");
  return lines.join("\\n");
}

export { tokens as theme };
`;
  }

  // tailwind — config extension object + cn() util
  return `// Generated by @icydotdev/lumen — Tailwind config extension.
import { tokens } from "./tokens";

export const theme = {
  extend: {
    colors: tokens.colors,
    spacing: tokens.spacing,
    borderRadius: tokens.borderRadius,
    boxShadow: tokens.shadows,
  },
};

// Spread into tailwind.config: theme: { extend: { ...themeExtension.extend } }
export const themeExtension = theme;
`;
}

// ── cn() util for tailwind ───────────────────────────────
function renderCnUtil(): string {
  return `// Minimal className combiner.
export function cn(...classes: Array<string | false | null | undefined>): string {
  return classes.filter(Boolean).join(" ");
}
`;
}

// ── component .tsx ───────────────────────────────────────
function renderComponent(
  c: ComponentInfo,
  approach: StylingApproach
): string {
  const variants = c.variants.length ? c.variants : ["default"];
  const variantUnion = variants.map((v) => `"${v}"`).join(" | ");

  if (approach === "styled-components") {
    return `import React from "react";
import styled from "styled-components";

export interface ${c.name}Props extends React.HTMLAttributes<HTMLDivElement> {
  variant?: ${variantUnion};
  children?: React.ReactNode;
}

const Styled${c.name} = styled.div<{ $variant: ${variantUnion} }>\`
  /* TODO(lumen): map variant → theme styles */
\`;

export function ${c.name}({ variant = "${variants[0]}", children, ...rest }: ${c.name}Props) {
  return (
    <Styled${c.name} $variant={variant} {...rest}>
      {children}
    </Styled${c.name}>
  );
}

export default ${c.name};
`;
  }

  if (approach === "css-modules") {
    return `import React from "react";
import styles from "./${c.name}.module.css";

export interface ${c.name}Props extends React.HTMLAttributes<HTMLDivElement> {
  variant?: ${variantUnion};
  children?: React.ReactNode;
}

export function ${c.name}({ variant = "${variants[0]}", children, className, ...rest }: ${c.name}Props) {
  return (
    <div className={[styles.${"base"}, styles[variant], className].filter(Boolean).join(" ")} {...rest}>
      {children}
    </div>
  );
}

export default ${c.name};
`;
  }

  // tailwind
  const variantMap = variants
    .map((v) => `  ${JSON.stringify(v)}: "", // TODO(lumen): variant classes`)
    .join("\n");

  return `import React from "react";
import { cn } from "../../lib/cn";

const variants: Record<string, string> = {
${variantMap}
};

export interface ${c.name}Props extends React.HTMLAttributes<HTMLDivElement> {
  variant?: ${variantUnion};
  children?: React.ReactNode;
}

export function ${c.name}({ variant = "${variants[0]}", children, className, ...rest }: ${c.name}Props) {
  return (
    <div className={cn(variants[variant], className)} {...rest}>
      {children}
    </div>
  );
}

export default ${c.name};
`;
}

// ── component .stories.tsx ───────────────────────────────
function renderStories(c: ComponentInfo): string {
  const variants = c.variants.length ? c.variants : ["default"];
  const stories = variants
    .map((v) => {
      const exportName = v.charAt(0).toUpperCase() + v.slice(1).replace(/[^A-Za-z0-9]/g, "");
      return `export const ${exportName}: Story = {
  args: { variant: "${v}", children: "${c.name}" },
};`;
    })
    .join("\n\n");

  return `import type { Meta, StoryObj } from "@storybook/react";
import { ${c.name} } from "./${c.name}";

const meta: Meta<typeof ${c.name}> = {
  title: "Components/${c.name}",
  component: ${c.name},
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ${c.name}>;

${stories}
`;
}

// ── component .test.tsx ──────────────────────────────────
function renderTest(c: ComponentInfo, config: ProjectConfig): string {
  const importLine =
    config.testRunner === "vitest"
      ? `import { describe, it, expect } from "vitest";`
      : ``;
  const variants = c.variants.length ? c.variants : ["default"];

  return `${importLine}
import { render, screen } from "@testing-library/react";
import { axe } from "jest-axe";
import { ${c.name} } from "./${c.name}";

describe("${c.name}", () => {
  it("renders its children", () => {
    render(<${c.name}>Hello</${c.name}>);
    expect(screen.getByText("Hello")).toBeInTheDocument();
  });

${variants
  .map(
    (v) => `  it("renders the ${v} variant", () => {
    const { container } = render(<${c.name} variant="${v}">${c.name}</${c.name}>);
    expect(container.firstChild).toBeTruthy();
  });`
  )
  .join("\n\n")}

  it("has no accessibility violations", async () => {
    const { container } = render(<${c.name}>Accessible</${c.name}>);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
`;
}

function renderIndex(name: string): string {
  return `export { ${name}, default } from "./${name}";
export type { ${name}Props } from "./${name}";
`;
}

function renderCssModule(c: ComponentInfo): string {
  const variants = c.variants.length ? c.variants : ["default"];
  return `.base {
  /* TODO(lumen): base styles */
}
${variants.map((v) => `.${v} {\n  /* TODO(lumen): ${v} variant */\n}`).join("\n")}
`;
}

function renderLumenConfig(config: ProjectConfig): string {
  return `// Generated by @icydotdev/lumen — config for future runs.
export const lumenConfig = {
  stylingApproach: ${JSON.stringify(config.stylingApproach)},
  testRunner: ${JSON.stringify(config.testRunner)},
  hasStorybook: ${config.hasStorybook},
} as const;
`;
}

export async function generate(opts: GenerateOptions): Promise<void> {
  const { config, scan, emit, dryRun } = opts;
  const approach = primaryApproach(scan.stylingApproach);
  const uiDir = path.join(config.rootPath, "ui");

  emit({ type: "scan_start" });

  // Top-level token + theme files
  write(path.join(uiDir, "tokens.ts"), renderTokensFile(scan.tokens), dryRun);
  for (const [name, value] of Object.entries(scan.tokens.colors)) {
    emit({ type: "token", kind: "colors", name, value });
  }
  write(path.join(uiDir, "theme.ts"), renderThemeFile(approach), dryRun);
  write(path.join(uiDir, "lumen.config.ts"), renderLumenConfig(config), dryRun);
  if (approach === "tailwind") {
    write(path.join(uiDir, "lib", "cn.ts"), renderCnUtil(), dryRun);
  }

  for (const inc of scan.inconsistencies) {
    emit({ type: "inconsistency", inconsistency: inc });
  }

  // Per-component
  for (const c of scan.components) {
    emit({ type: "component", component: c });
    emit({ type: "generating", name: c.name });

    const dir = path.join(uiDir, "components", c.name);
    write(path.join(dir, `${c.name}.tsx`), renderComponent(c, approach), dryRun);
    write(path.join(dir, `${c.name}.stories.tsx`), renderStories(c), dryRun);
    write(path.join(dir, `${c.name}.test.tsx`), renderTest(c, config), dryRun);
    write(path.join(dir, "index.ts"), renderIndex(c.name), dryRun);
    if (approach === "css-modules") {
      write(path.join(dir, `${c.name}.module.css`), renderCssModule(c), dryRun);
    }

    emit({ type: "generated", name: c.name });
  }

  emit({
    type: "complete",
    summary: {
      componentCount: scan.components.length,
      tokenCount:
        Object.keys(scan.tokens.colors).length +
        Object.keys(scan.tokens.spacing).length,
      inconsistencyCount: scan.inconsistencies.length,
    },
  });
}

// Inject `lumen` script into the user's package.json
export function injectScript(rootDir: string, dryRun: boolean): boolean {
  const pkgPath = path.join(rootDir, "package.json");
  if (!fs.existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    pkg.scripts = pkg.scripts || {};
    if (pkg.scripts.lumen) return false;
    pkg.scripts.lumen = "npx @icydotdev/lumen --dashboard";
    if (!dryRun) {
      fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
    }
    return true;
  } catch {
    return false;
  }
}
